# Generated by Django 3.1.7 on 2021-03-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=500)),
                ('space_description', models.CharField(max_length=1000)),
                ('space_max_capacity', models.IntegerField()),
                ('space_noise_level_allowed', models.IntegerField()),
                ('space_noise_level', models.IntegerField()),
                ('space_wifi', models.BooleanField()),
                ('space_restrooms', models.BooleanField()),
                ('space_food_drink', models.BooleanField()),
            ],
        ),
    ]
