# Generated by Django 3.1.7 on 2021-04-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_dt_full', models.DateTimeField()),
                ('space_dt_closed', models.BooleanField()),
                ('space_dt_reserved', models.BooleanField()),
                ('space_dt_reserved_by', models.CharField(max_length=1000)),
            ],
        ),
    ]
