# Generated by Django 3.1.7 on 2021-04-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedspaces', '0002_spacedatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacedatetime',
            name='space_dt_full',
        ),
        migrations.AddField(
            model_name='spacedatetime',
            name='space_date',
            field=models.CharField(default='EMPTY', max_length=100),
        ),
        migrations.AddField(
            model_name='spacedatetime',
            name='space_end_time',
            field=models.CharField(default='EMPTY', max_length=100),
        ),
        migrations.AddField(
            model_name='spacedatetime',
            name='space_start_time',
            field=models.CharField(default='EMPTY', max_length=100),
        ),
    ]
