# Generated by Django 3.1.7 on 2021-05-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedspaces', '0002_space_space_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_address2',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
