# Generated by Django 3.1.7 on 2021-04-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedspaces', '0003_auto_20210414_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='space_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spacedatetime',
            name='space_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharedspaces.space'),
        ),
        migrations.AlterField(
            model_name='spacedatetime',
            name='space_dt_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spacedatetime',
            name='space_dt_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spacedatetime',
            name='space_dt_reserved_by',
            field=models.CharField(default='No User', max_length=1000),
        ),
    ]
