# Generated by Django 3.1.7 on 2021-06-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedspaces', '0004_spacefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_spaces',
            field=models.ManyToManyField(to='sharedspaces.Space'),
        ),
    ]
