# Generated by Django 3.1.7 on 2021-04-16 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedspaces', '0004_auto_20210415_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='space_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
